import { proxy } from "valtio";

const state = proxy({
	intro: true,
	color: "#EFBD48",
	isFrontLogoTexture: true,
	isBackLogoTexture: true,
	isFrontText: true,
	isBackText: true,
	isFullTexture: false,
	frontLogoDecal: "./threejs.png",
	fullDecal: "./texture.jpeg",
	frontLogoPosition: [0, 0.04, 0.15] as [number, number, number],
	frontLogoScale: 0.15,
	backLogoDecal: "./threejs.png",
	backLogoPosition: [0, 0.04, -0.15] as [number, number, number],
	backLogoRotation: [0, Math.PI, 0] as [number, number, number],
	backLogoScale: 0.15,
	frontText: "Front Text",
	frontTextPosition: [0, -0.04, 0.15] as [number, number, number],
	frontTextRotation: [0, 0, 0] as [number, number, number],
	frontTextFontSize: 0.1,
	frontTextScale: [0.15, 0.04, 0.1] as [number, number, number],
	frontTextFont: "Arial",
	frontTextSize: 64,
	frontTextColor: "black",
	backText: "Back Text",
	backTextPosition: [0, -0.04, -0.15] as [number, number, number],
	backTextRotation: [0, Math.PI, 0] as [number, number, number],
	backTextFontSize: 0.1,
	backTextScale: [0.15, 0.04, 0.1] as [number, number, number],
	backTextFont: "Arial",
	backTextSize: 64,
	backTextColor: "white",
});

export default state;
